# GNU Affero General Public License v3.0 or later (see COPYING or https://www.gnu.org/licenses/agpl.txt)

FROM ghcr.io/t-c-l-o-u-d/linter-images/base-linter:latest

# install linter packages
RUN pacman --sync --refresh --noconfirm \
    bash \
    shellcheck \
    shellharden

# clean up pacman cache
RUN pacman --sync --clean --clean --noconfirm

COPY lint.bash /usr/local/bin/lint
COPY fix.bash /usr/local/bin/fix
RUN chmod +x /usr/local/bin/lint /usr/local/bin/fix

ENV LINTER_IMAGE=lint-bash

WORKDIR /workspace

LABEL org.opencontainers.image.authors "https://github.com/t-c-l-o-u-d"
LABEL org.opencontainers.image.description "Linter image for bash: shellcheck, shellharden"
LABEL org.opencontainers.image.licenses "AGPL-3.0-or-later"
LABEL org.opencontainers.image.source "https://github.com/t-c-l-o-u-d/linter-images"
