# GNU Affero General Public License v3.0 or later (see COPYING or https://www.gnu.org/licenses/agpl.txt)

FROM ghcr.io/t-c-l-o-u-d/linter-images/base-linter:latest

USER root

# install linter packages
RUN pacman --sync --refresh --noconfirm \
    ansible \
    ansible-lint

# clean up pacman cache
RUN pacman --sync --clean --clean --noconfirm

COPY lint.bash /usr/local/bin/lint
RUN chmod +x /usr/local/bin/lint

# redirect ansible state out of the (read-only) workspace
ENV ANSIBLE_HOME=/tmp/.ansible
ENV LINTER_IMAGE=lint-ansible

WORKDIR /workspace

USER 9001

LABEL org.opencontainers.image.authors "https://github.com/t-c-l-o-u-d"
LABEL org.opencontainers.image.description "Linter image for ansible: ansible-lint"
LABEL org.opencontainers.image.licenses "AGPL-3.0-or-later"
LABEL org.opencontainers.image.source "https://github.com/t-c-l-o-u-d/linter-images"
